---
#--------------------------

title: tigran - photos
description: 'Balancing life between the analog charm of film photography and the digital world of computers.'

url: 'https://tigransimonyan.com'

#--------------------------

# if your site type is Project Pages site, change below value to '/projectname'
baseurl: ''

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Asia/Yerevan

markdown: kramdown

sass:
  sass_dir: /assets/css
  style: compressed

exclude:
  - vendor # Avoid Jekyll mistakenly read the vendor directory on Travis-CI's VM .
  - Gemfile.lock
  - Gemfile
  - tools
  - README.md
